export const TODAY = '2026-06-10';

export const CATEGORIES = ['전체', '아동', '노인', '환경', '동물', '장애인', '기타'];

export const SLOTS = [
  {
    id: 1,
    orgName: '마포노인복지관',
    orgEmoji: '🏠',
    orgRating: 4.8,
    orgReviewCount: 124,
    title: '독거노인 말벗 봉사',
    category: '노인',
    categoryEmoji: '👴',
    date: '2026-06-10',
    timeStart: '14:00',
    timeEnd: '16:00',
    location: '서울 마포구 도화동',
    spotsTotal: 5,
    spotsLeft: 2,
    hours: 2,
    description: '혼자 사시는 어르신들과 대화를 나누며 정서적 지지를 드리는 봉사입니다. 특별한 기술 없이 따뜻한 마음만 있으면 충분합니다.',
    requirements: ['만 18세 이상', '사전 교육 없음', '편한 복장 착용'],
  },
  {
    id: 2,
    orgName: '서울동물보호소',
    orgEmoji: '🐾',
    orgRating: 4.6,
    orgReviewCount: 89,
    title: '유기견 산책 도우미',
    category: '동물',
    categoryEmoji: '🐕',
    date: '2026-06-10',
    timeStart: '10:00',
    timeEnd: '12:00',
    location: '서울 은평구 진관동',
    spotsTotal: 8,
    spotsLeft: 5,
    hours: 2,
    description: '보호 중인 유기견들의 산책을 도와주는 활동입니다. 강아지를 좋아하시는 분이라면 누구나 환영합니다.',
    requirements: ['동물 알레르기 없는 분', '편한 신발 착용'],
  },
  {
    id: 3,
    orgName: '초록우산 어린이재단',
    orgEmoji: '☂️',
    orgRating: 4.9,
    orgReviewCount: 201,
    title: '아동 학습 멘토링',
    category: '아동',
    categoryEmoji: '👦',
    date: '2026-06-11',
    timeStart: '15:00',
    timeEnd: '17:00',
    location: '서울 노원구 상계동',
    spotsTotal: 4,
    spotsLeft: 1,
    hours: 2,
    description: '초등학생을 대상으로 학습 멘토링을 진행하는 봉사입니다. 수학, 영어 등 교과 과목 도움 또는 독서 활동을 함께합니다.',
    requirements: ['대학생 이상', '교육 관련 경험 우대', '매뉴얼 제공'],
  },
  {
    id: 4,
    orgName: '환경운동연합',
    orgEmoji: '🌿',
    orgRating: 4.7,
    orgReviewCount: 156,
    title: '한강 플로깅 캠페인',
    category: '환경',
    categoryEmoji: '🌱',
    date: '2026-06-14',
    timeStart: '09:00',
    timeEnd: '11:00',
    location: '서울 영등포구 여의도한강공원',
    spotsTotal: 20,
    spotsLeft: 12,
    hours: 2,
    description: '한강변을 걸으며 쓰레기를 줍는 플로깅 봉사입니다. 운동도 하고 환경도 지키는 일석이조 활동으로 많은 분들의 참여를 기다립니다.',
    requirements: ['편한 복장 착용', '장갑·봉투 현장 제공', '야외 활동 가능한 분'],
  },
  {
    id: 5,
    orgName: '장애인자립생활센터',
    orgEmoji: '♿',
    orgRating: 4.5,
    orgReviewCount: 67,
    title: '장애인 이동 지원 봉사',
    category: '장애인',
    categoryEmoji: '♿',
    date: '2026-06-10',
    timeStart: '13:00',
    timeEnd: '15:00',
    location: '서울 강서구 화곡동',
    spotsTotal: 3,
    spotsLeft: 1,
    hours: 2,
    description: '지체장애인분들의 외출 및 이동을 보조해 드리는 봉사입니다. 따뜻한 배려심으로 함께해 주실 분을 기다립니다.',
    requirements: ['체력적으로 건강한 분', '현장 교육 30분 진행'],
  },
  {
    id: 6,
    orgName: '다문화가족지원센터',
    orgEmoji: '🌍',
    orgRating: 4.8,
    orgReviewCount: 93,
    title: '다문화 가정 한국어 교육',
    category: '기타',
    categoryEmoji: '🌍',
    date: '2026-06-12',
    timeStart: '10:00',
    timeEnd: '12:00',
    location: '서울 구로구 가리봉동',
    spotsTotal: 6,
    spotsLeft: 3,
    hours: 2,
    description: '다문화 가정 어머니들에게 한국어를 가르쳐 드리는 봉사입니다. 교원 자격증 없이도 참여 가능하며 교육 매뉴얼을 제공합니다.',
    requirements: ['한국어 능통자', '교육 매뉴얼 제공', '주 1회 정기 참여 권장'],
  },
];
